name: Retrain LSTM 1 Bulan

on:
  schedule:
    - cron: "0 1 1 * *" # Setiap tanggal 1 jam 01:00 UTC (08:00 WIB)
  workflow_dispatch: # Bisa dijalankan manual juga

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Setup Google Credentials
        env:
          GCP_CREDS: ${{ secrets.GCP_CREDS }}
        run: |
          echo "$GCP_CREDS" > time-series-analysis-480002-e7649b18ed82.json

      - name: Run LSTM 1 Bulan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/time-series-analysis-480002-e7649b18ed82.json
        run: |
          python lstm_1bulan.py
